services:
  tornei-padel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tornei-padel
    ports:
      - "10000:10000"
    restart: unless-stopped
    environment:
      - PORT=10000
